os: linux
language: shell

stages:
  - name: Deploy infra
  
services:
  - docker

install:
  - sudo apt-add-repository "deb http://archive.ubuntu.com/ubuntu trusty-backports main restricted universe multiverse"
  - sudo apt-get -qq update
  - sudo apt-get -t trusty-backports install shellcheck
  - sudo pip install awscli  


jobs:
  include:
    - stage: Deploy infra
      script:
        - echo "Feeding CloudFormation template with variables."
        - sed -i -e "s/STATETABLENAME/${terraform_table}/g" template_cloudformation.yml
        - sed -i -e "s/STATEBUCKETNAME/${terraform_bucket}/g" template_cloudformation.yml
        - sed -i -e "s/ARTIFACTBUCKETNAME/${artifact_bucket}/g" template_cloudformation.yml
        - sed -i -e "s/AIRLYTABLE/${dynamodb_airly}/g" template_cloudformation.yml
      deploy:
        provider: Cloudformation
        edge: true # use DPLv2
        access_key_id: ${AWS_ACCESS_KEY_ID}
        secret_access_key: ${AWS_SECRET_ACCESS_KEY}
        template: template_cloudformation.yml
        stack_name: Alexa-Airly-Infrastructure
        region: ${terraform_region}
        wait: true
        promote: true