AWSTemplateFormatVersion: "2010-09-09"
Description: Infrastructure for Alexa-Airly

Resources:
  TerraformStateBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: STATEBUCKETNAME
      BucketEncryption: 
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      Tags:
        - 
          Key: Name
          Value: STATEBUCKETNAME
        - 
          Key: Project
          Value: Alexa-Airly-Status
        - 
          Key: Purpose
          Value: Terraform State files

  ArtifactsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ARTIFACTBUCKETNAME
      VersioningConfiguration: 
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: ManageVersions
            Status: Enabled
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 1
            NoncurrentVersionExpirationInDays: 60
      BucketEncryption: 
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      Tags:
        - 
          Key: Name
          Value: ARTIFACTBUCKETNAME
        - 
          Key: Project
          Value: Alexa-Airly-Status
        - 
          Key: Purpose
          Value: Artifacts storage

  TerraformStateTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: LOCKTABLENAME
      BillingMode: "PAY_PER_REQUEST"
      AttributeDefinitions:
        -
          AttributeName: "LockID"
          AttributeType: "S"
      KeySchema: 
        -
          AttributeName: "LockID"
          KeyType: "HASH"
      Tags:
        -
          Key: Name
          Value: LOCKTABLENAME
        -
          Key: Project
          Value: Alexa-Airly-Status
        -
          Key: Purpose
          Value: Terraform Locks table

  DeployHashTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: DEPLOYHASH
      BillingMode: "PAY_PER_REQUEST"
      AttributeDefinitions:
        -
          AttributeName: "FunctionName"
          AttributeType: "S"
      KeySchema: 
        -
          AttributeName: "FunctionName"
          KeyType: "HASH"
      Tags:
        -
          Key: Name
          Value: DEPLOYHASH
        -
          Key: Project
          Value: Alexa-Airly-Status
        -
          Key: Purpose
          Value: Terraform Locks table

  AirlyTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: AIRLYTABLE
      BillingMode: "PAY_PER_REQUEST"
      AttributeDefinitions:
        -
          AttributeName: "Element"
          AttributeType: "S"
      KeySchema: 
        -
          AttributeName: "Element"
          KeyType: "HASH"
      Tags:
        -
          Key: Name
          Value: AIRLYTABLE
        -
          Key: Project
          Value: Alexa-Airly-Status
        -
          Key: Purpose
          Value: Airly data table
  
  AlexaAirlyTravisRole:
    Type: AWS::IAM::Role
    Properties:
      Description: IAM role for Travis execution created by Cloudformation
      Path: /alexaairly/
      RoleName: iam-role-for-travis-alexa-airly
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - s3.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: iam-policy-for-travis-alexa-airly
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - 
                Effect: Allow
                Action: 
                  - s3:ListBucket
                  - s3:GetObject
                  - s3:PutObject
                Resource: 
                  -
                    !Join
                      - ''
                      - - 'arn:aws:s3:::'
                        - !Ref TerraformStateBucket
                  -
                    !Join
                      - ''
                      - - 'arn:aws:s3:::'
                        - !Ref ArtifactsBucket
              -
                Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:DeleteItem
                Resource:
                  -
                    !Join
                      - ''
                      - - 'arn:aws:dynamodb:eu-west-1:ACCOUNTNUMBER:table/'
                        - !Ref TerraformStateTable
                  -
                    !Join
                      - ''
                      - - 'arn:aws:dynamodb:eu-west-1:ACCOUNTNUMBER:table/'
                        - !Ref AirlyTable
                  -
                    !Join
                      - ''
                      - - 'arn:aws:dynamodb:eu-west-1:ACCOUNTNUMBER:table/'
                        - !Ref DeployHashTable
Outputs:
  TerraformStateBucketName:
    Description: Terraform States bucket for AlexaAirly
    Value: !Ref TerraformStateBucket
    Export:
      Name: !Sub "${AWS::StackName}-TerraformStateBucket"

  ArtifactsBucketName:
    Description: Artifacts bucket for AlexaAirly
    Value: !Ref ArtifactsBucket
    Export:
      Name: !Sub "${AWS::StackName}-ArtifactsBucket"

  TerraformStateTableName:
    Description: Terraform Locks DynamoDB table for AlexaAirly
    Value: !Ref TerraformStateTable
    Export:
      Name: !Sub "${AWS::StackName}-TerraformStateTable"

  DeployHashTableName:
    Description: Deploy hashes DynamoDB table for AlexaAirly
    Value: !Ref DeployHashTable
    Export:
      Name: !Sub "${AWS::StackName}-DeployHashTable"

  AirlyTableName:
    Description: Data DynaloDB Table for AlexaAirly
    Value: !Ref AirlyTable
    Export:
      Name: !Sub "${AWS::StackName}-AirlyTable"
